package fes.aragon;

public enum Tokens {
	ASIGNACION,SUMA,MULTIPLICACION,RESTA,DIVICION,ID,INT,ERROR,ABSTRACT,BOOLEAN,
	BREAK,IDENTIFICADOR,IDENTIFICADORI,INTEGER_LITERAL,EQ,EQEQ,PLUS,STRING_LITERAL,IDENTIFIER
}
