package fes.aragon;

public enum Tokens {
	ABSOLUTE,ARRAY,BEGIN,CONST,DESTRUCTOR,DIV,DOWNTO,END,FOR,FUNCTION,IF,IN,
	INTERFACE,LABEL,NIL,OBJECT,OR,PRIVATE,PROGRAM,REPEAT,SHL,STRING,TO,UNIT,USES,
	VIRTUAL,WITH,AND,ERROR,IDENTIFIER,PLUS,INTEGER_LITERAL,EQ,EQEQ
}
